name: theme_demo
description: Theme mode toggle demo with Riverpod and ToggleButtons
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flex_color_scheme: ^1.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

