# This GitHub analyzes action, runs on pull to master.
#  - Installs Dart and flutter.
#  - Shows used dart and flutter version.
#  - Enables flutter web.
#  - Gets package dependencies.
#  - Run dart analyze.
#  - Show outdated packages.
#  - Verify that dart format is used by all committed code, fail if not.
name: Analyze ThemeDemo
on:
  push:
    branches: [none]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
jobs:
  run_tests:
    name: Analyze and check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter and Dart SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Show Dart SDK version
        run: dart --version

      - name: Show Flutter SDK version
        run: flutter --version

      - name: Install Flutter package dependencies
        run: flutter pub get

      - name: Analyze Dart source
        run: dart analyze

      - name: Show outdated packages
        run: flutter pub outdated

      - name: Verify that Dart formatting is used, fail if not
        run: dart format --output=none --set-exit-if-changed .
