# This GitHub build and  deploy runs on master publish, it:
#  - Installs Dart and flutter
#  - Uses Flutter beta channel for now.
#  - Enables flutter web
#  - Gets package dependencies
#  - Runs dart analyze, allows deprecation warnings, we on purpose allow use of deprecated features on beta channel,
#    as they might not yet be deprecated on stable and we will keep using some of the features that are deprecated
#    as long as they are not also deprecated on stable.
#  - Show outdated packages, just added for info.
#  - Verify that dart format is used by all committed code, fails if not. Controversial but pub.dev penalizes you if
#    dart format is not used.
#  - Upload code coverage output to Codecov for analysis.
#  - Install linux rpl tool. It is used to automate the needed change of a line in index.html.
#  - Build default and web example apps for FlexColorPicker.
#    - Flutter clean.
#    - Flutter build web app, in release mode and with CanvasKit renderer.
#  - This CI/CD stops here, it does not deploy, that is done by the deploy workflow, that is otherwise identical,
#    but runs on release, when it is published.
name: Build and Deploy Web ThemeDemo
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [none]
    paths-ignore:
      - "**.md"
  release:
    types: [published]
jobs:
  tests_build:
    name: Analyze, build and deploy ThemeDemo web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter and Dart SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Show Dart SDK version
        run: dart --version

      - name: Show Flutter SDK version
        run: flutter --version

      - name: Flutter Enable Web
        run: flutter config --enable-web

      - name: Install Flutter package dependencies
        run: flutter pub get

      - name: Analyze Dart source
        run: dart analyze

      - name: Show outdated packges
        run: flutter pub outdated

      - name: Verify that Dart formatting is used, fail if not
        run: dart format --output=none --set-exit-if-changed .

      # Build ThemeDemo Web app

      - name: DEFAULT EXAMPLE START BUILD - Flutter clean before build
        run: flutter clean && cd example && flutter clean

      - name: WEB EXAMPLE release build using CanvasKit
        run: cd example && flutter build web --web-renderer=canvaskit --base-href "/themedemo/" --release --target=lib/main.dart

      - name: WEB EXAMPLE DEPLOY to GitHub Pages repository, published on commit.
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/web/.'
          destination_folder: 'themedemo'
          destination_repo: 'rydmike/rydmike.github.io'
          user_email: 'm.rydstrom@gmail.com'
          user_name: 'rydmike'
